# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Error.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Error_Window(object):
    def setupUi(self, Error_Window):
        Error_Window.setObjectName("Error_Window")
        Error_Window.resize(240, 161)
        self.centralwidget = QtWidgets.QWidget(Error_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 50, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ErrorOkay = QtWidgets.QPushButton(self.centralwidget)
        self.ErrorOkay.setGeometry(QtCore.QRect(80, 100, 75, 23))
        self.ErrorOkay.setObjectName("ErrorOkay")
        Error_Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Error_Window)
        self.statusbar.setObjectName("statusbar")
        Error_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Error_Window)
        QtCore.QMetaObject.connectSlotsByName(Error_Window)

    def retranslateUi(self, Error_Window):
        _translate = QtCore.QCoreApplication.translate
        Error_Window.setWindowTitle(_translate("Error_Window", "MainWindow"))
        self.label.setText(_translate("Error_Window", "Please Complete the Form."))
        self.ErrorOkay.setText(_translate("Error_Window", "Okay"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Error_Window = QtWidgets.QMainWindow()
    ui = Ui_Error_Window()
    ui.setupUi(Error_Window)
    Error_Window.show()
    sys.exit(app.exec_())
